language: cpp
sudo: required
dist: trusty
compiler:
  - g++
os:
  - linux
install:
  - sudo apt-get install cmake
env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release
  global:
    - CI_HOME=`pwd`
script:
  - g++ --version
  - cmake --version
  - cd CI_HOME
  - pwd
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=release ..
  - make