language: cpp
sudo: required
dist: trusty
compiler:
  - g++
os:
  - linux
install:
  - sudo apt-get install cmake
  - sudo apt-get install libprotobuf-dev protobuf-compiler libprotoc-dev
  - PROTOC_ZIP=protoc-3.7.1-linux-x86_64.zip
  - curl -OL https://github.com/google/protobuf/releases/download/v3.7.1/$PROTOC_ZIP
  - sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
  - sudo unzip -o $PROTOC_ZIP -d /usr/local include/*
  - rm -f $PROTOC_ZIP
env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release

script:
  - SOURCE_DIR=`pwd`
  - g++ --version
  - cmake --version
  - cd $SOURCE_DIR
  - pwd
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=release ..
  - make