language: cpp
sudo: required
dist: trusty
compiler:
  - g++
os:
  - linux
install:
  - sudo apt-get install cmake
  - sudo apt-get install libprotobuf-dev protobuf-compiler libprotoc-dev
  - PROTOC_ZIP=protoc-3.7.1-linux-x86_64.zip
  - curl -OL https://github.com/google/protobuf/archive/v3.1.0.tar.gz
  - ls
  - tar xvzf v3.1.0.tar.gz
  - ls
  - cd protobuf-3.1.0/
  - ls
  - ./autogen.sh
  - ./configure  --prefix=/usr/local/protobuf
  - make
  - make check
  - make install
  - export PATH=$PATH:/usr/local/protobuf/bin
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/protobuf/lib
env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release

script:
  - SOURCE_DIR=`pwd`
  - cat /usr/local/include/google/protobuf/port_def.inc
  - g++ --version
  - cmake --version
  - cd $SOURCE_DIR
  - pwd
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=release ..
  - make