language: cpp
sudo: required
dist: trusty
compiler:
  - g++
os:
  - linux
install:
  - sudo apt-get install cmake
env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release
script:
  - SOURCE_DIR=`pwd`
    BUILD_DIR=${BUILD_DIR:-../build}
    BUILD_TYPE=${BUILD_TYPE:-release}

    mkdir -p $BUILD_DIR/$BUILD_TYPE \
    && cd $BUILD_DIR/$BUILD_TYPE \
    && cmake \
    -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
    $SOURCE_DIR \
    && make $*