language: cpp
sudo: required
dist: trusty
compiler:
  - g++
os:
  - linux
install:
  - sudo apt-get install cmake
  - sudo apt-get install libprotobuf-dev protobuf-compiler libprotoc-dev
  - sudo apt-get install autoconf automake libtool curl make g++ unzip
  - cd ..
  - pwd
  - git clone https://github.com/google/protobuf
  - ls
  - cd protobuf/
  - ls
  - ./autogen.sh
  - ./configure
  - make
  - make check
  - sudo make install
  - sudo ldconfig
  - cd ..
env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release

script:
  - cd beluga
  - SOURCE_DIR=`pwd`
  - find /usr/local -name port_def.inc
  - cat /usr/local/include/google/protobuf/port_def.inc
  - g++ --version
  - cmake --version
  - cd $SOURCE_DIR
  - pwd
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=release ..
  - make